---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-push-gcr:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm install

    # - name: Test
    #   run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'christosAAA'
        git config --global user.email 'christos.atzinas@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run styleguide:build
        mv styleguide build

    - name: Checkout
      uses: actions/deploy-pages@v1